version: "2"
services:
    www:
        build: .
        ports: 
            - "7001:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
    db:
        image: mariadb
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
